"""add email_is_verified to user model

Revision ID: 434fc8ac20f1
Revises: b8b25c5a0994
Create Date: 2025-11-21 17:18:16.154684

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "434fc8ac20f1"
down_revision: Union[str, Sequence[str], None] = "b8b25c5a0994"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email_is_verified", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_is_verified")
    # ### end Alembic commands ###
