"""add_scheduling_models

Revision ID: c8ba5e535419
Revises: 2e49518c922f
Create Date: 2026-01-18 18:58:21.414855

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8ba5e535419"
down_revision: Union[str, Sequence[str], None] = "2e49518c922f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institutions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_institutions_id"), "institutions", ["id"], unique=False)
    op.create_index(
        op.f("ix_institutions_user_id"), "institutions", ["user_id"], unique=False
    )
    op.create_table(
        "class_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("student_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_class_groups_id"), "class_groups", ["id"], unique=False)
    op.create_index(
        op.f("ix_class_groups_institution_id"),
        "class_groups",
        ["institution_id"],
        unique=False,
    )
    op.create_table(
        "constraints",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("constraint_type", sa.String(), nullable=False),
        sa.Column(
            "constraint_data", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_constraints_id"), "constraints", ["id"], unique=False)
    op.create_index(
        op.f("ix_constraints_institution_id"),
        "constraints",
        ["institution_id"],
        unique=False,
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("subject_code", sa.String(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lessons_id"), "lessons", ["id"], unique=False)
    op.create_index(
        op.f("ix_lessons_institution_id"), "lessons", ["institution_id"], unique=False
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("room_type", sa.String(), nullable=True),
        sa.Column("equipment", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rooms_id"), "rooms", ["id"], unique=False)
    op.create_index(
        op.f("ix_rooms_institution_id"), "rooms", ["institution_id"], unique=False
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("academic_period", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_schedules_id"), "schedules", ["id"], unique=False)
    op.create_index(
        op.f("ix_schedules_institution_id"),
        "schedules",
        ["institution_id"],
        unique=False,
    )
    op.create_table(
        "time_slots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("slot_number", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_time_slots_id"), "time_slots", ["id"], unique=False)
    op.create_index(
        op.f("ix_time_slots_institution_id"),
        "time_slots",
        ["institution_id"],
        unique=False,
    )
    op.create_table(
        "schedule_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("class_group_id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("time_slot_id", sa.UUID(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["class_group_id"], ["class_groups.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["time_slot_id"], ["time_slots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_schedule_entries_class_group_id"),
        "schedule_entries",
        ["class_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_entries_id"), "schedule_entries", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_schedule_entries_institution_id"),
        "schedule_entries",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_entries_lesson_id"),
        "schedule_entries",
        ["lesson_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_entries_room_id"),
        "schedule_entries",
        ["room_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_entries_schedule_id"),
        "schedule_entries",
        ["schedule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_entries_teacher_id"),
        "schedule_entries",
        ["teacher_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_entries_time_slot_id"),
        "schedule_entries",
        ["time_slot_id"],
        unique=False,
    )
    op.create_table(
        "students",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("class_group_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("student_number", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["class_group_id"], ["class_groups.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_students_class_group_id"), "students", ["class_group_id"], unique=False
    )
    op.create_index(op.f("ix_students_id"), "students", ["id"], unique=False)
    op.create_index(
        op.f("ix_students_institution_id"), "students", ["institution_id"], unique=False
    )
    op.create_table(
        "teacher_lessons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_teacher_lessons_id"), "teacher_lessons", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_teacher_lessons_lesson_id"),
        "teacher_lessons",
        ["lesson_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_lessons_teacher_id"),
        "teacher_lessons",
        ["teacher_id"],
        unique=False,
    )
    op.add_column("teachers", sa.Column("institution_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_teachers_institution_id"), "teachers", ["institution_id"], unique=False
    )
    op.create_foreign_key(
        None, "teachers", "institutions", ["institution_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teachers", type_="foreignkey")
    op.drop_index(op.f("ix_teachers_institution_id"), table_name="teachers")
    op.drop_column("teachers", "institution_id")
    op.drop_index(op.f("ix_teacher_lessons_teacher_id"), table_name="teacher_lessons")
    op.drop_index(op.f("ix_teacher_lessons_lesson_id"), table_name="teacher_lessons")
    op.drop_index(op.f("ix_teacher_lessons_id"), table_name="teacher_lessons")
    op.drop_table("teacher_lessons")
    op.drop_index(op.f("ix_students_institution_id"), table_name="students")
    op.drop_index(op.f("ix_students_id"), table_name="students")
    op.drop_index(op.f("ix_students_class_group_id"), table_name="students")
    op.drop_table("students")
    op.drop_index(
        op.f("ix_schedule_entries_time_slot_id"), table_name="schedule_entries"
    )
    op.drop_index(op.f("ix_schedule_entries_teacher_id"), table_name="schedule_entries")
    op.drop_index(
        op.f("ix_schedule_entries_schedule_id"), table_name="schedule_entries"
    )
    op.drop_index(op.f("ix_schedule_entries_room_id"), table_name="schedule_entries")
    op.drop_index(op.f("ix_schedule_entries_lesson_id"), table_name="schedule_entries")
    op.drop_index(
        op.f("ix_schedule_entries_institution_id"), table_name="schedule_entries"
    )
    op.drop_index(op.f("ix_schedule_entries_id"), table_name="schedule_entries")
    op.drop_index(
        op.f("ix_schedule_entries_class_group_id"), table_name="schedule_entries"
    )
    op.drop_table("schedule_entries")
    op.drop_index(op.f("ix_time_slots_institution_id"), table_name="time_slots")
    op.drop_index(op.f("ix_time_slots_id"), table_name="time_slots")
    op.drop_table("time_slots")
    op.drop_index(op.f("ix_schedules_institution_id"), table_name="schedules")
    op.drop_index(op.f("ix_schedules_id"), table_name="schedules")
    op.drop_table("schedules")
    op.drop_index(op.f("ix_rooms_institution_id"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_lessons_institution_id"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_constraints_institution_id"), table_name="constraints")
    op.drop_index(op.f("ix_constraints_id"), table_name="constraints")
    op.drop_table("constraints")
    op.drop_index(op.f("ix_class_groups_institution_id"), table_name="class_groups")
    op.drop_index(op.f("ix_class_groups_id"), table_name="class_groups")
    op.drop_table("class_groups")
    op.drop_index(op.f("ix_institutions_user_id"), table_name="institutions")
    op.drop_index(op.f("ix_institutions_id"), table_name="institutions")
    op.drop_table("institutions")
    # ### end Alembic commands ###
