"""create group-lesson-pairs

Revision ID: d510a55d15d3
Revises: f194eebeadc5
Create Date: 2026-01-24 22:16:32.961643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'd510a55d15d3'
down_revision: Union[str, Sequence[str], None] = 'f194eebeadc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_group_lessons',
    sa.Column('class_group_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_group_id', 'lesson_id')
    )
    op.create_table('study_group_lessons',
    sa.Column('study_group_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_group_id', 'lesson_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_group_lessons')
    op.drop_table('class_group_lessons')
    # ### end Alembic commands ###
