"""create study_groups

Revision ID: f194eebeadc5
Revises: c8ba5e535419
Create Date: 2026-01-22 14:55:04.541407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f194eebeadc5"
down_revision: Union[str, Sequence[str], None] = "c8ba5e535419"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "streams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_streams_id"), "streams", ["id"], unique=False)
    op.create_index(
        op.f("ix_streams_institution_id"), "streams", ["institution_id"], unique=False
    )
    op.create_table(
        "stream_class_groups",
        sa.Column("stream_id", sa.UUID(), nullable=False),
        sa.Column("class_group_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_group_id"], ["class_groups.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["stream_id"], ["streams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("stream_id", "class_group_id"),
    )
    op.create_table(
        "study_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("stream_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["stream_id"], ["streams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_study_groups_id"), "study_groups", ["id"], unique=False)
    op.create_index(
        op.f("ix_study_groups_institution_id"),
        "study_groups",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_groups_stream_id"), "study_groups", ["stream_id"], unique=False
    )
    op.create_table(
        "study_group_students",
        sa.Column("study_group_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["study_group_id"], ["study_groups.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("study_group_id", "student_id"),
    )
    op.add_column(
        "schedule_entries", sa.Column("study_group_id", sa.UUID(), nullable=True)
    )
    op.alter_column(
        "schedule_entries", "class_group_id", existing_type=sa.UUID(), nullable=True
    )
    op.create_index(
        op.f("ix_schedule_entries_study_group_id"),
        "schedule_entries",
        ["study_group_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "schedule_entries",
        "study_groups",
        ["study_group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "schedule_entries", type_="foreignkey")
    op.drop_index(
        op.f("ix_schedule_entries_study_group_id"), table_name="schedule_entries"
    )
    op.alter_column(
        "schedule_entries", "class_group_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("schedule_entries", "study_group_id")
    op.drop_table("study_group_students")
    op.drop_index(op.f("ix_study_groups_stream_id"), table_name="study_groups")
    op.drop_index(op.f("ix_study_groups_institution_id"), table_name="study_groups")
    op.drop_index(op.f("ix_study_groups_id"), table_name="study_groups")
    op.drop_table("study_groups")
    op.drop_table("stream_class_groups")
    op.drop_index(op.f("ix_streams_institution_id"), table_name="streams")
    op.drop_index(op.f("ix_streams_id"), table_name="streams")
    op.drop_table("streams")
    # ### end Alembic commands ###
